CREATE TABLE ESPECTACULO (COD NUMBER, NOMBRE VARCHAR2(20), LUGAR VARCHAR2(20), FECHA DATE, PRIMARY KEY (COD));
INSERT INTO ESPECTACULO VALUES(1111,'Pelicula','San Martin','10-03-2019');
INSERT INTO ESPECTACULO VALUES(1118,'Teatro','San Martin','20-07-2019');
INSERT INTO ESPECTACULO VALUES(1113,'Pelicula','Botika','15-10-2019');
INSERT INTO ESPECTACULO VALUES(1114,'Pelicula','Antzoki','30-12-2019');
COMMIT;

SELECT NAME, VALUE FROM V$PARAMETER WHERE NAME = 'global_names';

CREATE DATABASE LINK GIPUZKOA.GI.EHU.ES CONNECT TO DBDC07 IDENTIFIED BY DBDC07 USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = vsids11.si.ehu.es)(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME = GIPUZKOA.gi.ehu.es)))';

SELECT * FROM ACTOR@GIPUZKOA.GI.EHU.ES;

SELECT TITULO, NOMBRE FROM PELICULAS@GIPUZKOA.GI.EHU.ES PELIS, ESPECTACULO WHERE PELIS.COD = ESPECTACULO.COD;

INSERT INTO ACTOR@GIPUZKOA.GI.EHU.ES VALUES(666, 'Iker Lara', 'Euskal Herria');
COMMIT;
SELECT * FROM ACTOR@GIPUZKOA.GI.EHU.ES;

CREATE SYNONYM MISPELICULAS FOR PELICULAS@GIPUZKOA.GI.EHU.ES;

SELECT TITULO, NOMBRE FROM MISPELICULAS, ESPECTACULO WHERE ESPECTACULO.COD=MISPELICULAS.COD;

INSERT INTO MISPELICULAS VALUES(6666,'My Life','Iker Lara');
COMMIT;
SELECT * FROM PELICULAS@GIPUZKOA.GI.EHU.ES;
