CREATE TABLE PELICULAS (COD NUMBER, TITULO VARCHAR2(20), DIRECTOR VARCHAR2(20), PRIMARY KEY (COD));
INSERT INTO PELICULAS VALUES(1111,'Gran Torino','Clint Eastwood');
INSERT INTO PELICULAS VALUES(1112,'Avatar','James Cameron');
INSERT INTO PELICULAS VALUES(1113,'Los Increíbles','Brad Bird');
INSERT INTO PELICULAS VALUES(1114,'True Grit','Henry Hathaway');
COMMIT;
CREATE TABLE ACTOR (DNI NUMBER, NOMBRE VARCHAR2(20), PAIS VARCHAR2(20), PRIMARY KEY (DNI));
INSERT INTO ACTOR VALUES(111, 'Ignacio Zuloaga', 'Euskal Herria');
INSERT INTO ACTOR VALUES(112, 'Pablo Picasso', 'España');
INSERT INTO ACTOR VALUES(113, 'Vincent Van Gogh', 'Holanda');
INSERT INTO ACTOR VALUES(114, 'Claude Monet','Francia');
INSERT INTO ACTOR VALUES(115, 'Salvador Dalí', 'España');
COMMIT;

SELECT NAME, VALUE FROM V$PARAMETER WHERE NAME = 'global_names';

CREATE DATABASE LINK ARABA.GI.EHU.ES CONNECT TO DBDC07 IDENTIFIED BY DBDC07 USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = vsids11.si.ehu.es)(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME = ARABA.gi.ehu.es)))';

SELECT * FROM ESPECTACULO@ARABA.GI.EHU.ES;

ALTER SESSION SET GLOBAL_NAMES=FALSE;
-- EN TEORIA NO SE REFLEJARA EN DBA->CONEXIONES->CONFIGURACION DE LA BD->PARAMETROS DE INICIALIZACION, PERO SI SE VE CON EL SELECT
SELECT NAME, VALUE FROM V$PARAMETER WHERE NAME = 'global_names';
CREATE DATABASE LINK PRUEBA CONNECT TO DBDC07 IDENTIFIED BY DBDC07 USING 'ARABA';

SELECT * FROM ESPECTACULO@PRUEBA;

-- CON GLOBAL_NAMES = TRUE TODO LO QUE SALGA DE GIPUZKOA TIENE QUE LLAMARSE COMO LA TABLA A LA QUE VA, CON GLOBAL_NAMES = FALSE NO HACE FALTA.