DROP TABLE PEDIDO_PRECIO;
DROP TABLE PIDE;
DROP TABLE EMPLEADO_CLIENTE;
DROP TABLE COMPRA;
DROP TABLE CLIENTE;
DROP TABLE DIRIGE;
DROP TABLE EMPLEADO;
DROP TABLE MARCA;
DROP TABLE NO_PERSONALIZADA;
DROP TABLE PERSONALIZADA;
DROP TABLE MATERIAS;
DROP TABLE CAMISETA;
DROP TABLE ALMACEN;
DROP TABLE TIENDA;
DROP TABLE PROVEEDOR;
DROP TABLE FABRICA;
CREATE TABLE FABRICA (
    NIF_F VARCHAR2(9) NOT NULL,
    Pais VARCHAR2(15),
    Direccion VARCHAR2(50),
    Nombre VARCHAR2(20),
    Telefono NUMBER,
    PRIMARY KEY(NIF_F)
);
CREATE TABLE PROVEEDOR (
    NIF_P VARCHAR2(9) NOT NULL,
    Direccion VARCHAR2(50),
    Telefono NUMBER,
    PRIMARY KEY(NIF_P)
);
CREATE TABLE TIENDA (
    NIF_T VARCHAR2(9) NOT NULL,
    Direccion VARCHAR2(50),
    Nombre VARCHAR2(20),
    Telefono NUMBER,
    PRIMARY KEY(NIF_T)
);
CREATE TABLE ALMACEN (
    NIF_F VARCHAR2(9),
    IdAlmacen NUMBER NOT NULL,
    FOREIGN KEY (NIF_F) REFERENCES FABRICA (NIF_F),
    PRIMARY KEY (NIF_F, IdAlmacen)
);
CREATE TABLE CAMISETA (
    CodCamiseta NUMBER NOT NULL,
    Tipo VARCHAR2(15),
    Color VARCHAR2(20),
    FechaFabr DATE,
    Talla CHAR(3),
    NIF_F VARCHAR2(9),
    IdAlmacen NUMBER,
    Lote VARCHAR2(25),
    FOREIGN KEY (NIF_F, IdAlmacen) REFERENCES ALMACEN (NIF_F, IdAlmacen),
    PRIMARY KEY(CodCamiseta)
);
CREATE TABLE MATERIAS (
    CodCamiseta NUMBER,
    Materia VARCHAR2(20) NOT NULL,
    FOREIGN KEY (CodCamiseta) REFERENCES CAMISETA (CodCamiseta),
    PRIMARY KEY(CodCamiseta, Materia)
);
CREATE TABLE PERSONALIZADA (
    CodCamiseta NUMBER,
    DisenoPersonalizado VARCHAR2(25),
    FOREIGN KEY (CodCamiseta) REFERENCES CAMISETA (CodCamiseta),
    PRIMARY KEY(CodCamiseta)
);
CREATE TABLE NO_PERSONALIZADA (
    CodCamiseta NUMBER,
    DisenoTemporada VARCHAR2(25),
    FOREIGN KEY (CodCamiseta) REFERENCES CAMISETA (CodCamiseta),
    PRIMARY KEY(CodCamiseta)
);
CREATE TABLE MARCA (
    CodCamiseta NUMBER,
    Marca VARCHAR2(10),
    FOREIGN KEY (CodCamiseta) REFERENCES CAMISETA (CodCamiseta),
    PRIMARY KEY(CodCamiseta)
);
CREATE TABLE EMPLEADO (
    DNI_E VARCHAR2(9) NOT NULL,
    Nombre VARCHAR2(15),
    Apellido1 VARCHAR2(15),
    Apellido2 VARCHAR2(15),
    Sexo CHAR(1),
    Domicilio VARCHAR2(50),
    Telefono NUMBER,
    NSS NUMBER(11),
    FechaNacim DATE,
    Puesto VARCHAR2(20),
    FechaIni DATE,
    Sueldo NUMBER,
    NIF_Empresa VARCHAR2(9),
    Jornada VARCHAR2(10),
    Horas NUMBER,
    -- FOREIGN KEY (NIF_Empresa) REFERENCES FABRICA (NIF_F),
    FOREIGN KEY (NIF_Empresa) REFERENCES TIENDA (NIF_T),
    PRIMARY KEY (DNI_E)
);
CREATE TABLE DIRIGE (
    DNI_Jefe VARCHAR2(9),
    DNI_Empl VARCHAR2(9),
    FOREIGN KEY (DNI_Jefe) REFERENCES EMPLEADO (DNI_E),
    FOREIGN KEY (DNI_Empl) REFERENCES EMPLEADO (DNI_E),
    PRIMARY KEY(DNI_Jefe, DNI_Empl)
);
CREATE TABLE CLIENTE (
    DNI_C VARCHAR2(9) NOT NULL,
    Nombre VARCHAR2(15),
    Apellido1 VARCHAR2(15),
    Apellido2 VARCHAR2(15),
    Sexo CHAR(1),
    Domicilio VARCHAR2(50),
    Telefono NUMBER,
    FechaNacim DATE,
    PRIMARY KEY (DNI_C)
);
CREATE TABLE COMPRA (
    NIF_T VARCHAR2(9),
    DNI_C VARCHAR2(9),
    Descuento VARCHAR2(15),
    FOREIGN KEY (NIF_T) REFERENCES TIENDA (NIF_T),
    FOREIGN KEY (DNI_C) REFERENCES CLIENTE (DNI_C),
    PRIMARY KEY(NIF_T, DNI_C)
);
CREATE TABLE EMPLEADO_CLIENTE (
    DNI_EC VARCHAR2(9),
    DescEmpl VARCHAR2(15),
    FOREIGN KEY (DNI_EC) REFERENCES CLIENTE (DNI_C),
    FOREIGN KEY (DNI_EC) REFERENCES EMPLEADO (DNI_E),
    PRIMARY KEY(DNI_EC)
);
CREATE TABLE PIDE (
    NIF_T VARCHAR2(9),
    NIF_P VARCHAR2(9),
    NIF_F VARCHAR2(9),
    IdAlmacen NUMBER,
    NumPedido NUMBER NOT NULL,
    Fecha DATE NOT NULL,
    FOREIGN KEY (NIF_T) REFERENCES TIENDA (NIF_T),
    FOREIGN KEY (NIF_P) REFERENCES PROVEEDOR (NIF_P),
    FOREIGN KEY (NIF_F, IdAlmacen) REFERENCES ALMACEN (NIF_F, IdAlmacen),
    PRIMARY KEY (NIF_T, NIF_P, NIF_F, IdAlmacen, NumPedido, Fecha)
);
CREATE TABLE PEDIDO_PRECIO (
    NumPedido NUMBER,
    Fecha DATE,
    Precio NUMBER,
    -- FOREIGN KEY (NumPedido, Fecha) REFERENCES PIDE (NumPedido, Fecha),
    PRIMARY KEY (NumPedido, Fecha)
);